# Generated by Django 5.2.4 on 2025-08-25 22:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_parent_user_parent_email_parent_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('months', models.PositiveIntegerField(help_text='Number of months to split into')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_plans', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFeeInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_no', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='core.studentfeeplan')),
            ],
            options={
                'ordering': ('plan_id', 'sequence_no'),
                'unique_together': {('plan', 'sequence_no')},
            },
        ),
    ]
